### ISSUE TITLE
Undefined functions and Python packages

### ISSUE THREAD

**Issue by gewitterblitz** [MeteoSwiss/fast-barnes-py#1] opened 2023-02-21 04:25 UTC
Hi,

I just came across this Github repository and the associated paper in GMD. It looks really neat. While trying to reproduce some of the figures in the paper, I realized that the packages 'reader' and 'plotmap' are not specified in the requirements.txt file. Also, I could not find them on PyPI or using google search. Could you please clarify?

Thanks!

**Comment by z10o** [comment] 2023-02-26 09:45
Hi gewitterblitz,
the Python scripts required to reproduce the figures and tables from the paper are only contained in the 'demo' directory here on GitHub. To clarify how these results can be reproduced, I added now a new document 'doc/ReproduceResults_Doc.md', which gives instructions on how to proceed. Hope this helps!

**Comment by milindsharma1** [comment] 2023-02-26 18:38
Ah, I see. Apologies for the confusion. 

I tried `fastbarnes` with some weather radar data (2D RHI scan) and it was amazingly fast. Thank you sharing it with the community.

I'll close this issue since it's resolved now.

**Closed as completed by milindsharma1** 2023-02-26 18:38 UTC
